### ISSUE TITLE
Reconsider how styling is done

### ISSUE THREAD

**Issue by JonAlexandra** [alexandrainst/DanskeTestfaciliteter#20]
Presently it is a confusing mess of dkdfs utility classes/components, local css classes and imported local files.

**Comment by MagnusHBrunbjerg** [comment]
Note to self: The EFP sandbox app makes use of [globally redefined mediaquery mixins](https://github.com/Erhvervsfremmeplatformen/tredjepartsapps/blob/master/src/styles/mixins/_mediaquery-helpers.scss), these are clearly pulled from DKFDS [properties](https://github.com/detfaellesdesignsystem/dkfds-components/blob/e0ae5a1dca7dfadfe20e9d611adfacd56a5d5eb4/src/stylesheets/core/_properties.scss#L101) and [breakpoints](https://github.com/detfaellesdesignsystem/dkfds-components/blob/e0ae5a1dca7dfadfe20e9d611adfacd56a5d5eb4/src/stylesheets/core/mixins/_breakpoints.scss), why? Does the EFP platform customize them or is this meant to be a way to redefine and customize them for application implementations?
