### ISSUE TITLE
Remove physical and virtual labels

### ISSUE THREAD

**Issue by SofieHansen** [alexandrainst/DanskeTestfaciliteter#30]
![Udklip](https://github.com/alexandrainst/DanskeTestfaciliteter/assets/139336152/3c1c8c81-2498-4f3a-8598-9a6d5b533fab)

**Comment by JonAlexandra** [comment]
Are we completely removing the physical/virtual distinction or are we just removing/changing how it is done in the UI?

**Comment by JonAlexandra** [comment]
> Are we completely removing the physical/virtual distinction or are we just removing/changing how it is done in the UI?

We are just removing it from the UI. We will probably still have the labels somewhere in the description of the facilities.
