### ISSUE TITLE
Better way of handling facility placement on the map

### ISSUE THREAD

**Issue by MagnusHBrunbjerg** [alexandrainst/DanskeTestfaciliteter#38]
Some facilities in the dataset seem to not contain lat/long data, which is currently used for placing the facilities on the map, they do however all contain an address.

Currently the lat/long data is used for placing them on the map which means not all facilities are placed on the map, if possible consider using the address instead.

**Comment by JonAlexandra** [comment]
This is an issue with the data. When getting the new data, we need to make sure we get this data for all facilities.

**Comment by MagnusHBrunbjerg** [comment]
As noted above this will be handled in the backend.
