### ISSUE TITLE
Consider scrolling ux

### ISSUE THREAD

**Issue by JonAlexandra** [alexandrainst/DanskeTestfaciliteter#39]
Having two components which together have full width and potentially full-ish height and both have scrolling interaction can make for an annoying experience, if you are trying to navigate to the top or bottom of the page.

**Comment by MagnusHBrunbjerg** [comment]
Might be worth considering `ctrl+scroll` zoom and two finger pan implementations for desktop and mobile respectively. This seems to be a pretty common approach on other sites to deal with similar issues.
