### ISSUE TITLE
Ensure our current icon system will work with VG

### ISSUE THREAD

**Issue by JonAlexandra** [alexandrainst/DanskeTestfaciliteter#54]
It is the recommended way by dkfds, but we include it at a point where we have no control, so we need to ensure that they have this properly set up at VG

**Comment by MagnusHBrunbjerg** [comment]
The way they are currently injected is to mimic the way the VG platform is set up and injects it globally on their site. In order to avoid relying on their icon setup we should probably just change it to inject the actual dkfds icons at app root.
